// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface BlogPost {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  reading_time?: number;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  content?: PortableTextBlock[];
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  technologies?: unknown;
  live_url?: string;
  github_url?: string;
  featured?: boolean;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SiteConfig {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  role_title?: string;
  email?: string;
  location?: string;
  company?: string;
  role?: string;
  previous_role?: string;
  avatar?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_title_line1?: string;
  hero_title_line2?: string;
  hero_description?: string;
  hero_primary_cta?: string;
  hero_primary_cta_href?: string;
  hero_secondary_cta?: string;
  hero_secondary_cta_href?: string;
  technologies?: unknown;
  availability_status?: string;
  availability_message?: string;
  response_time?: string;
  best_topics?: unknown;
  contact_cta_title?: string;
  contact_cta_description?: string;
  copyright_text?: string;
  built_with_text?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SocialLink {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  icon?: string;
  href?: string;
  handle?: string;
  description?: string;
  color?: string;
  is_primary?: boolean;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface UsesItem {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  reasoning?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  use_category?: string;
  url?: string;
  price?: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    posts: BlogPost;
    projects: Project;
    site_config: SiteConfig;
    social_links: SocialLink;
    uses: UsesItem;
  }
}